---
- hosts: Rundeckce
  become: yes
  remote_user: vagrant
  vars:
    maven_version: 3.5.2
    rundeck_version: 2.10.4-1.46
  tasks:
    - name: Update all packages to latest
      yum: name=* state=latest

    - name: Install git package
      yum: name={{ item }} state=present
      with_items:
       - git
       - vim

    - name: Copy jdk rpm
      copy: src=jdk-8u151-linux-x64.rpm dest=/tmp/jdk-8u151-linux-x64.rpm

    - name: Install jdk rpm
      yum: name=/tmp/jdk-8u151-linux-x64.rpm state=present

    - name: Copy Rundeck config rpm
      copy: src=rundeck-config-{{ rundeck_version }}.GA.noarch.rpm dest=/tmp/rundeck-config-{{ rundeck_version }}.GA.noarch.rpm

    - name: Copy Rundeck rpm
      copy: src=rundeck-{{ rundeck_version }}.GA.noarch.rpm dest=/tmp/rundeck-{{ rundeck_version }}.GA.noarch.rpm

    - name: Install Rundeck rpm
      yum: 
        name: /tmp/rundeck-config-{{ rundeck_version }}.GA.noarch.rpm, /tmp/rundeck-{{ rundeck_version }}.GA.noarch.rpm
        state: present

    - name: Copy Rundeck Config
      copy: src=rundeck-config.properties dest=/etc/rundeck/rundeck-config.properties

    - service:
        name: rundeckd
        state: started